# Generated by Django 5.0.6 on 2024-06-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerprofile',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
    ]
