# Generated by Django 5.0.6 on 2024-06-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0002_alter_dealerprofile_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerprofile',
            name='company_address',
            field=models.TextField(max_length=255),
        ),
    ]
