# Generated by Django 5.0.6 on 2024-06-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('dealer', 'dealer'), ('customer', 'Customer')], max_length=10),
        ),
    ]
